-- AlterTable
ALTER TABLE "Artist" ALTER COLUMN "grammy" SET DEFAULT false;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
